site_name: MkDocs Notes Template
repo_url: https://github.com/example/repository/
repo_name: SOME-NAME
site_description: My Site description
site_author: Miro Adamy
copyright: (c) 2020 Miro Adamy

nav:
    - Home: index.md
    - Demo:
        - Markdown: markdown-demo.md
        - Macros: macros-demo1.md
theme: 
    name: material

markdown_extensions:
    - admonition
    - codehilite  
    - toc:
        permalink: True
    - sane_lists

plugins:
    - search
    - macros:
        include_dir: .

extra:
    price: 12.50
    company:
        name: Acme
        address: Laurinska 8
        website: https://www.acme.com/    